### PR TITLE
Add direction argument to shift! calls in readme

### PR DESCRIPTION
**Pull request by Casper-Guo**
The example code segment in the `README.md` will not run successfully.

```
using CircularList

function main()
    h = circularlist(0)      # CircularList.List(0)
    insert!(h, 1)            # CircularList.List(1,0)
    shift!(h, 2, :forward)             # CircularList.List(1,2,0)
end

main()
```

throws

`LoadError: MethodError: no method matching shift!(::CircularList.List{Int64}, ::Int64)`

Rewrote readme to include the `direction` argument. The changed example segment now runs correctly.

### CODE REVIEW

**Comment by tk3369** [comment]
You are probably using an old version. See PR #9 
I will bump the version of the package. 
Thanks for the report.

**Comment by Casper-Guo** [comment]
I installed the package via REPL this morning (Julia 1.9.1 if that's relevant). Any idea why I might have received an outdated version?

**Comment by tk3369** [comment]
It was because this package was not tagged with a new version yet. I have now done that, so if you run the "up" command from the package mode now you should have the latest version 1.2.0.

**Comment by tk3369** [comment]
Just to be clear, the Julia version 1.9.1 isn't relevant. When you install this package (by doing something like `add CircularList` from the package mode in the REPL), it would install the current version at that time, which was version 1.1.0 and that was released a while back. However, GitHub shows the main/master branch by default, which contains the latest unreleased version.

When I saw your note here, I decided to update the package release to version 1.2.0, and also merged a few outstanding PRs. If you install the package again (or upgrade it), you should get the latest version now.

**Pull request closed without merging**
